%% path continuation - initialize_structs
%
%   Institute of Dynamics and Vibration Research
%   Leibniz University Hannover
%   16.09.2021 - Alwin Förster
%
function [Bifurcation,Counter,Do,Info,Initial,Path,Plot,Solver,Step_size_information] = initialize_structs(var0,l_start,l_end,Opt)
    %% Bifurcation
    %
    Bifurcation = struct('bif',[],...
                         'dirs',{cell(1,2)},...
                         'flag',0);
    %
    %% Counter
    %
    Counter = struct('catch',0,...
                     'catch_old',0,...
                     'error',0,...
                     'loop',0,...
                     'remove',0,...
                     'step',0,...
                     'valid_stepback',0);
    %
    %% Do
    %
    Do = struct('continuation',false,...
                'convergeToTarget',false,...
                'deflate',false,...
                'homotopy',false,...
                'loop',false,...
                'remove',false,...
                'stepback',false,...
                'suspend',false);
	%
    %% Info
    %
    Info = struct('exitflag',-1,...
                  'exit_msg','',...
                  'nv',numel(var0),...
                  'l_start',l_start,...
                  'l_end',l_end);
	%
    %% Initial
    %
    Initial = struct('ds_max',Opt.ds_max);
    %
    %% Path
    %
    Path = struct('l_all',[],...
                  's_all',[],...
                  'var_all',[]);
	%
    %% Plot
    %
    if (ison(Opt.plot) && ~Opt.plot.detail) || ~ison(Opt.plot)
        Plot = struct('fig',[],...
                      'pl',[],...
                      'pl_curr',[]);
    else
        Plot = struct('fig',[],...
                      'pl',[],...
                      'pl_cor',[],...
                      'pl_cor_assist',[],...
                      'pl_curr',[],...
                      'pl_det',[],...
                      'pl_it',[],...
                      'pl_pre',[],...
                      'pl_s',[]);
    end
	%
    %% Solver
    %
    [solver,predictor_solver,num_jac_solver,default_solver_output] = continuation_solver(Opt);
    Solver = struct('default_output',default_solver_output,...
                    'main',solver,...
                    'num_jac',num_jac_solver,...
                    'predictor',predictor_solver);
    %
    %% Step size information
    %
    Step_size_information = struct('rate_of_convergence', [],...
                                   'solver_output', [],...
                                   'speed_of_continuation', [],...
                                   'x_predictor', []);
                               
    Step_size_information = struct('current', Step_size_information,...
                                   'previous', []);
    %
end