%% path continuation - aux.initializeStructs
%
%   Institute of Dynamics and Vibration Research
%   Leibniz University Hannover
%   16.09.2021 - Alwin Förster
%   06.08.2022 - Anna Lefken
%
function [Bifurcation,Counter,Do,Info,InfoOut,Initial,Is,Jacobian,Path,Plot,Plus,Remove,Solver,StepsizeInformation,Temp] = initializeStructs(var0,lStart,lEnd,ds0,Opt,outputFlag)
    %% Bifurcation
    %
    Bifurcation = struct('bif',[],...
                         'dirs',{cell(1,2)},...
                         'flag',0,...
                         'scaling',[]);
    %
    %% Counter
    %
    Counter = struct('bifStepsizeRed',0,...
                     'catch',0,...
                     'catchOld',0,...
                     'closedCurve',0,...
                     'error',0,...
                     'event',0,...
                     'loop',0,...
                     'remove',0,...
                     'step',0,...
                     'validStepback',0);
    %
    %% Do
    %
    Do = struct('changeCorrector',false,...
                'continuation',false,...
                'convergeToTarget',false,...
                'deflate',false,...
                'homotopy',false,...
                'loop',false,...
                'remove',false,...
                'stepback',false,...
                'stepbackManually',false,...
                'stopManually',false,...
                'suspend',false);
	%
    %% Info
    %
    Info = struct('biDirRuns',0,...
                  'ds0',ds0,...
                  'exitflag',-1,...
                  'exitMsg','',...
                  'nv',numel(var0),...
                  'lStart',lStart,...
                  'lEnd',lEnd,...
                  'var0',var0);
	%
    %% InfoOut
    %
    InfoOut = struct('numberOfSteps',0,...
                     'numberOfInvalidPoints',0);
    %
    %% Initial
    %
    Initial = struct('dsMax',Opt.dsMax,...
                     'dsMin',Opt.dsMin);
    %
    %% Is
    %
    Is = struct('catch',false,...
                'currentJacobian',false,...
                'reverse',false,...
                'valid',false);
    %
    %% Jacobian
    %
    Jacobian = struct('initial',[],...
                      'last',[],...
                      'previous',[],...
                      'signDet',1,...
                      'solver',[]);
    %
    %% Path
    %
    Path = struct('lAll',[],...
                  'sAll',[],...
                  'speedOfContinuation',[],...
                  'varAll',[],...
                  'xPredictor',[],...
                  'biftestValue',[],...
                  'pathInfoValue',[]);
	%
    %% Plot
    %
    if (aux.ison(Opt.plot) && ~Opt.plot.detail) || ~aux.ison(Opt.plot)
        Plot = struct('fig',[],...
                      'pl',[],...
                      'plCurr',[]);
    else
        Plot = struct('fig',[],...
                      'pl',[],...
                      'plCor',[],...
                      'plCorAssist',[],...
                      'plCurr',[],...
                      'plDet',[],...
                      'plIt',[],...
                      'plPre',[],...
                      'plS',[]);
    end
	%
    %% Plus
    %
    Plus = struct('jacobian',[],...
                  'rateOfContraction',[],...
                  'speedOfContinuation',[],...
                  'x',[],...
                  'xPredictor',[]);
    %
    %% Remove
    %
    Remove = struct('ds',NaN,...
                    's',NaN);
    %
    %% Solver
    %
    [solver,predictorSolver,numJacSolver,defaultSolverOutput] = continuation.solver(Opt,outputFlag);
    Solver = struct('defaultOutput',defaultSolverOutput,...
                    'exitflag',-2,...
                    'main',solver,...
                    'numJac',numJacSolver,...
                    'output',defaultSolverOutput,...
                    'predictor',predictorSolver);
    %
    %% StepsizeInformation
    %
    StepsizeInformation = struct('rateOfContraction',NaN,...
                                  'speedOfContinuation',NaN);
    %
    %% Temp
    %
    Temp = struct('flag',[],...
                  'iterations',[],...
                  'length',[],...
                  'predictor',[],...
                  'rateOfContraction',[],...
                  'speedOfContinuation',[]);
    %
end